### ISSUE TITLE
Todo for develop/processing branch

### ISSUE THREAD

**Issue by james-dietz** [MALRO-DEV/LootHunter#1]
- [ ] Catch ESI 502s and resend request
- [ ] Implement a caching layer over ESI requests to reduce server load
- [ ] Add deployment instructions
- [ ] Clean up documentation
